import type { RequestHandler } from 'express';
import { ValidationError } from '../../core/errors/app-error.js';
import { attachAssetSchema, createProfileSchema, deviceOverrideSchema, deviceProfileSchema, profileIdSchema, updateProfileSchema } from './radio-profiles.schema.js';
import type { RadioProfilesService } from './radio-profiles.service.js';

export function createRadioProfilesController(service: RadioProfilesService) {
  const list: RequestHandler = async (_req, res, next) => { try { return res.json({ success: true, data: { profiles: await service.list() }, message: 'Radio profiles fetched' }); } catch (e) { return next(e); } };
  const create: RequestHandler = async (req, res, next) => { const body = createProfileSchema.safeParse(req.body); if (!body.success) return next(new ValidationError('Invalid radio profile payload')); try { return res.status(201).json({ success: true, data: { profile: await service.create(body.data) }, message: 'Radio profile created' }); } catch (e) { return next(e); } };
  const get: RequestHandler = async (req, res, next) => { const params = profileIdSchema.safeParse(req.params); if (!params.success) return next(new ValidationError('Invalid radio profile ID')); try { const profile = await service.get(params.data.id); return profile ? res.json({ success: true, data: { profile }, message: 'Radio profile fetched' }) : res.status(404).json({ success: false, error: 'Radio profile not found' }); } catch (e) { return next(e); } };
  const update: RequestHandler = async (req, res, next) => { const params = profileIdSchema.safeParse(req.params); const body = updateProfileSchema.safeParse(req.body); if (!params.success || !body.success) return next(new ValidationError('Invalid radio profile payload')); try { const profile = await service.update(params.data.id, body.data); return profile ? res.json({ success: true, data: { profile }, message: 'Radio profile updated' }) : res.status(404).json({ success: false, error: 'Radio profile not found' }); } catch (e) { return next(e); } };
  const remove: RequestHandler = async (req, res, next) => { const params = profileIdSchema.safeParse(req.params); if (!params.success || Object.keys(req.body ?? {}).length) return next(new ValidationError('Invalid radio profile delete request')); try { return await service.delete(params.data.id) ? res.json({ success: true, data: null, message: 'Radio profile deleted' }) : res.status(404).json({ success: false, error: 'Radio profile not found' }); } catch (e) { return next(e); } };
  const attachAsset: RequestHandler = async (req, res, next) => { const params = profileIdSchema.safeParse(req.params); const body = attachAssetSchema.safeParse(req.body); if (!params.success || !body.success) return next(new ValidationError('Invalid radio profile asset')); try { const asset = await service.attachAsset(params.data.id, { songId: body.data.song_id, slotType: body.data.slot_type, sortOrder: body.data.sort_order }); return asset ? res.json({ success: true, data: { asset }, message: 'Radio profile asset attached' }) : res.status(404).json({ success: false, error: 'Radio profile or song not found' }); } catch (e) { return next(e); } };
  const detachAsset: RequestHandler = async (req, res, next) => { const params = profileIdSchema.safeParse(req.params); const songId = typeof req.params['songId'] === 'string' ? req.params['songId'] : ''; const slotType = req.params['slotType']; if (!params.success || !/^[0-9a-f-]{36}$/i.test(songId) || (slotType !== 'jingle' && slotType !== 'ad')) return next(new ValidationError('Invalid radio profile asset')); try { return await service.detachAsset(params.data.id, songId, slotType) ? res.json({ success: true, data: null, message: 'Radio profile asset detached' }) : res.status(404).json({ success: false, error: 'Radio profile asset not found' }); } catch (e) { return next(e); } };
  const assignDevice: RequestHandler = async (req, res, next) => { const deviceId = typeof req.params['deviceId'] === 'string' ? req.params['deviceId'] : ''; const body = deviceProfileSchema.safeParse(req.body); if (!/^[0-9a-f-]{36}$/i.test(deviceId) || !body.success) return next(new ValidationError('Invalid device profile assignment')); try { const device = await service.assignDevice(deviceId, body.data.radio_profile_id); return device ? res.json({ success: true, data: { device }, message: 'Device profile assignment updated' }) : res.status(404).json({ success: false, error: 'Device or profile not found' }); } catch (e) { return next(e); } };
  const overrideDevice: RequestHandler = async (req, res, next) => { const deviceId = typeof req.params['deviceId'] === 'string' ? req.params['deviceId'] : ''; const body = deviceOverrideSchema.safeParse(req.body); if (!/^[0-9a-f-]{36}$/i.test(deviceId) || !body.success) return next(new ValidationError('Invalid device radio profile override')); try { const device = await service.updateDeviceOverride(deviceId, { override_enabled: body.data.override_enabled, autoplay_spotify_playlist_uri: body.data.autoplay_spotify_playlist_uri, jingle_every_n_songs: body.data.jingle_every_n_songs, ad_break_interval_minutes: body.data.ad_break_interval_minutes }); return device ? res.json({ success: true, data: { device }, message: 'Device radio profile override updated' }) : res.status(404).json({ success: false, error: 'Device not found' }); } catch (e) { return next(e); } };
  return { list, create, get, update, remove, attachAsset, detachAsset, assignDevice, overrideDevice };
}
