import type { RequestHandler } from 'express';
import { AppError, NotFoundError, ValidationError } from '../../../core/errors/app-error.js';
import { blockArtistSchema, blockedKeywordSchema, emptyModerationBodySchema, emptyModerationQuerySchema, moderationIdSchema, moderationSettingsSchema, moderationTestSchema } from './moderation-admin.schema.js';
import type { ModerationAdminService } from './moderation-admin.service.js';

export function createModerationAdminController(service: ModerationAdminService) {
  const blockSong: RequestHandler = async (req, res, next) => { const p = moderationIdSchema.safeParse(req.params); if (!p.success || !emptyModerationBodySchema.safeParse(req.body ?? {}).success || !emptyModerationQuerySchema.safeParse(req.query).success) return next(new ValidationError('Invalid song block request')); try { const song = await service.blockSong(p.data.id); return song ? res.json({ success: true, data: song, message: 'Song blocked' }) : next(new NotFoundError('Song not found')); } catch (e) { return next(e); } };
  const unblockSong: RequestHandler = async (req, res, next) => { const p = moderationIdSchema.safeParse(req.params); if (!p.success || !emptyModerationBodySchema.safeParse(req.body ?? {}).success || !emptyModerationQuerySchema.safeParse(req.query).success) return next(new ValidationError('Invalid song block request')); try { const song = await service.unblockSong(p.data.id); return song ? res.json({ success: true, data: song, message: 'Song unblocked' }) : next(new NotFoundError('Song not found')); } catch (e) { return next(e); } };
  const blockArtist: RequestHandler = async (req, res, next) => { const b = blockArtistSchema.safeParse(req.body); if (!b.success || !req.user || !emptyModerationQuerySchema.safeParse(req.query).success) return next(new ValidationError('Invalid blocked artist request')); try { const data = await service.addArtist({ ...b.data, blockedBy: req.user.userId }); return res.status(201).json({ success: true, data, message: 'Artist blocked' }); } catch (e) { return next(e); } };
  const unblockArtist: RequestHandler = async (req, res, next) => { const p = moderationIdSchema.safeParse(req.params); if (!p.success || !emptyModerationBodySchema.safeParse(req.body ?? {}).success || !emptyModerationQuerySchema.safeParse(req.query).success) return next(new ValidationError('Invalid blocked artist ID')); try { return res.json({ success: true, data: await service.removeArtist(p.data.id), message: 'Artist unblocked' }); } catch (e) { return next(e); } };
  const blocked: RequestHandler = async (req, res, next) => { if (!emptyModerationQuerySchema.safeParse(req.query).success) return next(new ValidationError('Unexpected moderation query parameters')); try { return res.json({ success: true, data: await service.listBlocked() }); } catch (e) { return next(e); } };
  const getSettings: RequestHandler = async (req, res, next) => { if (!emptyModerationQuerySchema.safeParse(req.query).success) return next(new ValidationError('Unexpected moderation query parameters')); try { return res.json({ success: true, data: await service.getSettings() }); } catch (e) { return next(e); } };
  const updateSettings: RequestHandler = async (req, res, next) => { const b = moderationSettingsSchema.safeParse(req.body); if (!b.success || !emptyModerationQuerySchema.safeParse(req.query).success) return next(new ValidationError('Invalid moderation settings')); try { const mapped = { ...(b.data.lyrics_filter_enabled !== undefined ? { lyrics_filter_enabled: b.data.lyrics_filter_enabled } : {}), ...(b.data.block_unverified_obscure_tracks !== undefined ? { block_unverified_obscure_tracks: b.data.block_unverified_obscure_tracks } : {}), ...(b.data.min_popularity_without_lyrics !== undefined ? { min_popularity_without_lyrics: Math.max(0, Math.min(100, Math.round(b.data.min_popularity_without_lyrics))) } : {}) }; return res.json({ success: true, data: await service.updateSettings(mapped), message: 'Moderation settings updated' }); } catch (e) { return next(e); } };
  const keywords: RequestHandler = async (req, res, next) => { if (!emptyModerationQuerySchema.safeParse(req.query).success) return next(new ValidationError('Unexpected moderation query parameters')); try { return res.json({ success: true, data: await service.listKeywords() }); } catch (e) { return next(e); } };
  const addKeyword: RequestHandler = async (req, res, next) => { const b = blockedKeywordSchema.safeParse(req.body); if (!b.success || !emptyModerationQuerySchema.safeParse(req.query).success) return next(new ValidationError('Invalid blocked keyword')); try { return res.status(201).json({ success: true, data: await service.addKeyword(b.data), message: 'Blocked keyword added' }); } catch (e) { return next(e); } };
  const removeKeyword: RequestHandler = async (req, res, next) => { const p = moderationIdSchema.safeParse(req.params); if (!p.success || !emptyModerationBodySchema.safeParse(req.body ?? {}).success || !emptyModerationQuerySchema.safeParse(req.query).success) return next(new ValidationError('Invalid keyword ID')); try { return res.json({ success: true, data: await service.removeKeyword(p.data.id), message: 'Blocked keyword removed' }); } catch (e) { return next(e); } };
  const test: RequestHandler = async (req, res, next) => { const b = moderationTestSchema.safeParse(req.body); if (!b.success || !emptyModerationQuerySchema.safeParse(req.query).success) return next(new ValidationError('Invalid moderation test request')); try { return res.json({ success: true, data: await service.test(b.data) }); } catch (e) { if (e instanceof AppError) return next(e); return next(new Error('Moderation test failed', { cause: e })); } };
  return { blockSong, unblockSong, blockArtist, unblockArtist, blocked, getSettings, updateSettings, keywords, addKeyword, removeKeyword, test };
}
